name: Docker Compose CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build and run containers
      run: docker-compose up --build -d

    - name: Wait for application to be ready
      run: sleep 120

    - name: Test application
      run: |
        curl -s --retry 3 --retry-delay 5 http://localhost:8080/ || exit 1

    - name: Tear down containers
      run: docker-compose down